# Generated by Django 5.2 on 2025-04-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="Subscription",
            field=models.ManyToManyField(to="auth.permission"),
        ),
    ]
