# Generated by Django 5.2 on 2025-04-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_subscription_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="Subscription",
            new_name="permissions",
        ),
    ]
