# Generated by Django 5.2 on 2025-05-02 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscriptionprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(
                default=True, help_text="Featured on Django pricing page"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(
                default=-1, help_text="Ordering on Django pricing page"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscription",
            ),
        ),
    ]
