# Generated by Django 5.2 on 2025-05-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0009_subscriptionprice_featured_subscriptionprice_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={"ordering": ["order", "featured", "-updated"]},
        ),
    ]
