# Generated by Django 5.2 on 2025-05-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Features for pricing, seperated by new line",
                null=True,
            ),
        ),
    ]
