# Generated by Django 5.2 on 2025-05-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0014_usersubscription_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="user_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
