# Generated by Django 5.2 on 2025-05-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0017_usersubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
    ]
